spring.application.name=client-service
server.port=8082
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3307/clients_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USER:payment_user}
spring.datasource.password=${DB_PASSWORD:payment_pass}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/migration/V1__create_clients.sql
management.endpoints.web.exposure.include=health,info
